language: julia
julia:
  - 1.0
  - 1.1
  - nightly
jobs:
  fast_finish: true
  include:
    - stage: "Linux"
      os: linux
    - stage: "macOS"
      os: osx
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - bash ./docs/travis.sh
      after_success: skip
  allow_failures:
    - julia: nightly
    - os: osx
    - stage: "Documentation"
codecov: true
coveralls: true
notifications:
  email: false
