language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly 0.7
    - os: osx
notifications:
  email: false
codecov: true
coveralls: true
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - bash ./docs/travis.sh
      after_success: skip
