language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - nightly

jobs:
  allow_failures:
    - julia: nightly
    - stage: "Documentation"
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --color=yes --project=docs -e 'using Pkg; Pkg.instantiate()'
        - travis_wait 30 julia --color=yes --project=docs docs/make.jl
      after_success: skip
  fast_finish: true

notifications:
  email: false

codecov: true
coveralls: true
