# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - release
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("GeometricIntegrators", coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'Pkg.add("Coverage")'
  - julia -e 'cd(Pkg.dir("GeometricIntegrators")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("GeometricIntegrators")); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("GeometricIntegrators")); using Coverage; Coveralls.submit(process_folder())'
