language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - nightly

jobs:
  allow_failures:
    - julia: nightly
    - stage: "Documentation"
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script: travis_wait 30 bash ./docs/travis.sh
      after_success: skip
  fast_finish: true

notifications:
  email: false

codecov: true
coveralls: true
